<?php

/**
 * @file
 * Install content to be used later in tests.
 */

/**
 * Implements hook_install().
 */
function cu_dc_bundle_tests_install() {
  // Install text block beans.
  $beans[0] = array(
    'title' => 'Text Block A',
    'content' => 'Text Block A Content AAA',
    'delta' => 'block-a-1'
  );

  $beans[1] = array(
    'title' => 'Text Block B',
    'content' => 'Text Block B Content BBB',
    'delta' => 'block-b-2'
  );

  foreach ($beans as $key => $value) {
    $bean = bean_create(array('type' => 'block'));
    $bean->label = $value['title'];
    $bean->title = $value['title'];
    $bean->delta = $value['delta'];
    $bean->field_block_text = array(
      LANGUAGE_NONE => array(array(
        'value' => $value['content'],
      )),
    );
    $bean->save();
  }
}

/**
 * Implements hook_enable().
 *
 * Set block field autocomplete to be a select list.
 */
function cu_dc_bundle_tests_enable() {
  $instance_info = field_info_instance('field_collection_item', 'field_block', 'field_block_option');

  $instance_info['widget']['type'] = 'options_select';
  $instance_info['widget']['module'] = 'options';

  field_update_instance($instance_info);
}
